### ISSUE TITLE
SET PROXY  IP:PORT|username(optional)|password(optional)

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#1]
The SET command itself already exists, so this is about adding a new feature to it. This also means adding support for it in the Kantu editor (in this it is something very basic like adding the value to the dropdown).

All SET values are active only for the macro run they are in. So afterwards we are back to the default (in this case: no proxy

**Comment by kuznetsoffandrey** [comment]
Implemented set proxy function. If parameter value is empty string, the proxy is disabled. The proxy is also disabled at the end of the script run

**Comment by teamdocs** [comment]
ok

**Comment by teamdocs** [comment]
I tested this command and it seems it does not work. Anything wrong with my settings? The same proxy settings work fine when used in the normal settings, "just" inside a command they have no effect (but also no error)


![iptest](https://user-images.githubusercontent.com/20772857/35681859-15052f0c-075f-11e8-82c5-d02efb1d804d.png)

Proxy itself works:
![ok](https://user-images.githubusercontent.com/20772857/35681860-151fe266-075f-11e8-9d64-08a3ee5b6f92.png)

**Comment by teamdocs** [comment]
works!
