### ISSUE TITLE
minor UI tweaks in settings panel

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#13]
See screenshot:

- input fields should be greyed out when option is not selected
- move "Test button" up (save space)

![uistuff](https://user-images.githubusercontent.com/20772857/33907736-7365b1d0-df86-11e7-94b7-755befd27ead.jpg)

**Comment by kuznetsoffandrey** [comment]
They are disabled for now. Will grey out them and move button

**Comment by kuznetsoffandrey** [comment]
Fixed
