### ISSUE TITLE
Pressing stop should  stop the loop completely

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#14]
One new discovered issue: If in a loop, pressing stop should  stop the loop completely,  currently it just stops the macro run.. so if I run a loop from 1... 100 I might have to press stop 99 times ;)

![stopbutton1](https://user-images.githubusercontent.com/20772857/33950251-3d87523e-e02c-11e7-9f46-351d613caee1.jpg)

**Comment by kuznetsoffandrey** [comment]
Easy to fix! Will do in a moment

**Comment by kuznetsoffandrey** [comment]
Fixed
