### ISSUE TITLE
After "errorignore" is used, macro displays stays after macro end

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#17]
See screenshot... once an "ignored error" is there, itdoes not switch back at macro end.

Expected:

1. Error is encountered and error message shown (and error logged to log file)
2. Before the next step, the error message is removed again 

=> error message shows up only  quickly. If more errors are encountered this repeats for all errors within the "errorignore=true" range

![errorignore1](https://user-images.githubusercontent.com/20772857/34119463-8eb5ae2c-e422-11e7-8048-d36cde5e9dc0.jpg)

**Comment by kuznetsoffandrey** [comment]
Checked and added a fix to remove errormessage until new error appears. Error message is also cleared on script finish

**Comment by teamdocs** [comment]
Overall this works nicely now, but I found an edge case where it does not work yet:

If there are two or more commands with errors in a sequence the error dialog does not get removed. So now the "old" error still shows during the image search of the 2nd command.

Expected result:

- error dialog shows after 1st command (ok)
- error dialog is removed at start of 2nd command... and then shows again shortly after the 2nd command has also an error

![secondcommandhaserror](https://user-images.githubusercontent.com/20772857/34952964-c170ceb4-fa1b-11e7-841f-ff15c8470946.jpg)

**Comment by kuznetsoffandrey** [comment]
Could not find a way to remove it according to the current macro run process yet. Need to do deeper analysis

**Comment by kuznetsoffandrey** [comment]
Added fade collapsing with animation when error is shown. Looks much better now.

**Comment by teamdocs** [comment]
ok, nice!
