### ISSUE TITLE
Regression issue: Kantu freezes if macro has no open command

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#18]
It seems to happen with every macro. Test macro attached. This works fine in the last released version, so it is a regression issue.

This one is important, it is a blocker for the release of the new version

Test macro:

[noopen-Demo-Automate-Forms.zip](https://github.com/teamdocs/kantu2018/files/1569717/noopen-Demo-Automate-Forms.zip)

**Comment by kuznetsoffandrey** [comment]
Fixed and tested

**Comment by teamdocs** [comment]
ok!
