### ISSUE TITLE
Drag and Drop: Visual indicator (trace) missing

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#19]
...as discussed in chat (just to log it)

Ideally you can mark start/endpoints with green frames and then show the pink trace during the drag.

**Comment by kuznetsoffandrey** [comment]
Added implementation with animation. Need to discuss how it is better to show this visual indicator. I am not sure tracing of movement is needed, but I will try this version also

**Comment by teamdocs** [comment]
Looks fine. But a visual trace of the path would be even better. ;-)

It will be especially useful if drag and drop does not work (say on HTML5), so users sees that the actually dragging takes place.

**Comment by kuznetsoffandrey** [comment]
Ok. Will add it and we will see how it works

**Comment by kuznetsoffandrey** [comment]
Added trace visualization
