### ISSUE TITLE
Codepen scroll does not work yet

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#20]
i did a few more tests with codepen, and scroll never works. Maybe this is the same issue as #29 ?

Here is another scrollbar with the same issue (I think codepen is[ using](https://blog.codepen.io/2015/02/26/custom-scrollbars/) them). The bar only makes one jump.
http://codemirror.net/demo/simplescrollbars.html

[001ddcusomscrollbars1.zip](https://github.com/teamdocs/kantu2018/files/1656141/001ddcusomscrollbars1.zip)

Scroll on many other sites works.

**Comment by kuznetsoffandrey** [comment]
Seems the error is due to html5 usage (as well as #29 ). This problem needs much deeper analysis of CefSharp engine.
Tried https://www.w3schools.com/html/html5_draganddrop.asp - doesn't work
Tried http://jqueryui.com/droppable/#default - works OK

**Comment by teamdocs** [comment]
Sigh... yeah. It seems we are talking about this issue: https://groups.google.com/forum/#!topic/cefsharp/jxXr6L9L7N0 and I am unsure if this is resolved or not.

So I removed #29 from being a blocker. => Lets ignore this issue for now and complete everything else. 

Then we can:
- upgrade to latest CEFSharp (should be ready by then) and see if it magically goes away. If not, lets discuss again.
