### ISSUE TITLE
Images are not shown for d&d command in sidebar

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#21]
See screenshot:
![dd1](https://user-images.githubusercontent.com/20772857/34921088-b28c52a4-f97d-11e7-8255-dc7098912d10.jpg)

Minor visual issue

**Comment by kuznetsoffandrey** [comment]
The same issue is for LimitSearchArea command. Double issue in fact

**Comment by teamdocs** [comment]
Hi... I just noticed this is also a regression issue: No image is shown for EXTRACT command as well! This works fine in previous version.

maybe that info helps finding out what is wrong...

**Comment by kuznetsoffandrey** [comment]
Fixed... no problem with extract though
