### ISSUE TITLE
editor: first image of d&d should "survive" when switching between click/extract and d&d commands

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#22]
...like it does now when switching between click, click&type and extract. Currently the image is "lost" and an X displayed.

Minor issue (ctrl+z undo works, nice)

**Comment by kuznetsoffandrey** [comment]
Can not reproduce it

**Comment by teamdocs** [comment]
I guess I did not explain this well... here is a screencast:
https://www.screencast.com/t/GtqOxZ19JeNl

It is the same issue with same for LimitSearchArea.

So for D&D:
- Switch from Click/Find to D&D: Click image becomes first AND second image of D&D
- Switch from D&D to Click/Find/... => First image of d&d is used. 2nd image is lost.

**Comment by kuznetsoffandrey** [comment]
Added confidence value surviving also. And fixed a bug when change type from Click to ClickRight/ClickType

**Comment by teamdocs** [comment]
nice!
