### ISSUE TITLE
If "no proxy" is selected the text of the proxy settings should be greyedout as well

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#24]
See the screenshot:

![greyout](https://user-images.githubusercontent.com/20772857/34953051-12a0bb46-fa1c-11e7-8b61-1c8b5be45896.jpg)

**Comment by kuznetsoffandrey** [comment]
Fixed

**Comment by teamdocs** [comment]
I see no change... the text (IP, Username, Port, Password) is not greyed out, but only the input boxes, just like before.

**Comment by kuznetsoffandrey** [comment]
Just did not commit this change yet. Will be in next commit
