### ISSUE TITLE
Same with Drag & Drop, ...was: Editor crashes when I try to save LimitSearchArea image

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#25]
Sequence:
- record macro
- open macro in editor
- Click (+) to duplicate a CLICK command
- Change type to LimitSearchArea
- Take Screenshot
- Save image => crash!

See also this screencast https://www.screencast.com/t/aFlg9eIGlZd

**Comment by kuznetsoffandrey** [comment]
Fixed. This was not a regression bug. Every extract command with change image name gave this error due to a bug.

**Comment by teamdocs** [comment]
> Every extract command with change image name gave this error due to a bug.

Yep...  thanks for fixing this!

**Comment by teamdocs** [comment]
It seems I get the same crash wit D&D. It also crashes with the default names (no renaming).  This prevents me from creating new d&d commands and testing further. Well, it's late anyway here.

![dd crash](https://user-images.githubusercontent.com/20772857/35199493-e42cc394-fefe-11e7-88f6-40b9e3968a7b.jpg)
