### ISSUE TITLE
 error EVEN SO there is a pink rectangle, was: no error message when green/pink rectangle are missing in LimitSearchArea

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#26]
Currently the command is processed and fails silently?

Expected: Error message.... just like with the EXTRACT command:

![expected no green](https://user-images.githubusercontent.com/20772857/35198935-b9c5e818-fef6-11e7-821b-23bbdc5c8d6b.jpg)

Important: Above screenshot is from previous version (https://a9t9.com/download ). In the current release EXTRACT command fails with strange error with pink/green rectangle are missing - it gets stuck and the timer counts up forever. Maybe related to #21 ?

![new version](https://user-images.githubusercontent.com/20772857/35198971-28a3748a-fef7-11e7-8702-b855371cebce.jpg)

**Comment by kuznetsoffandrey** [comment]
Added error messages for D&D and limitsearcharea commands

**Comment by teamdocs** [comment]
Almost fixed... but now there is an error EVEN SO there is a pink rectangle (d&d command works!)

![ddtest-nopink2](https://user-images.githubusercontent.com/20772857/35247202-cfcaf4b8-ffc9-11e7-95d4-954276cce871.jpg)

**Comment by kuznetsoffandrey** [comment]
Fixed
