### ISSUE TITLE
d&d does not work on https://html5demos.com/drag/

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#29]
Test website: https://html5demos.com/drag/

I see the same behavior on some other websites. It seems the item is not dragged at all. 
Any idea what could be wrong here?

test macro attached
[001dd3-html5.zip](https://github.com/teamdocs/kantu2018/files/1655769/001dd3-html5.zip)

I made this ticket blocker because I see the same issue inside the users' website that is waiting for the the  d&d feature ;-( ...we should at least understand why this is not working.

**Comment by teamdocs** [comment]
Same here: https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_draganddrop2

It seems the question is if this old issue is solved or not: https://groups.google.com/forum/#!topic/cefsharp/jxXr6L9L7N0

**Comment by kuznetsoffandrey** [comment]
Added comment to the first bug #20 
I suppose the problem is a common one

**Comment by teamdocs** [comment]
I added some comments to #20 and will add the issue to the backlog. I understand it is beyond the scope of this milestone. That being said, if you find a solution it will be absolutely bonus-worthy! ;-)

Some discussion also here: https://github.com/cefsharp/CefSharp/issues/1593
