### ISSUE TITLE
(3) SET ERRORIGNORE yes

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#3]
=> If YES, then macro execution does not stop at error. Instead it is only logged and the next command is executed. Another SET SET ERRORIGNORE no in the same macro would turn the normal mode on. This is useful if you want to (for example) search and click an image only if it exits.

**Comment by kuznetsoffandrey** [comment]
Added and tested. Error messagebox appears, then goes 2 sec delay and then macro continues its work. Replay and Continue buttons are disabled while ErrorIgnore stays YES.
At the end of the macro the ErrorIgnore sets to NO.

**Comment by teamdocs** [comment]
Hmmm... does not work for me. I tried with "yes" and with "true" (it should be true/false, so it fits with other commands)

![errorignoretest](https://user-images.githubusercontent.com/20772857/33908108-9dde932c-df87-11e7-9154-fe0af05fbad8.png)

**Comment by kuznetsoffandrey** [comment]
Like with sidebar. Write YES in upper case. Will check it and change to true false

**Comment by kuznetsoffandrey** [comment]
Fixed
