### ISSUE TITLE
D&d and LimitSearchArea need to display "timeout counter" (like all other image commands)

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#31]
Currently it seems they wait and fail silently if the image they are looking for is not on the page.

![notimer](https://user-images.githubusercontent.com/20772857/35281579-827b61ae-0053-11e8-88ec-4f4d6c2b4f76.jpg)

Expected: A timer like here:

![waiting](https://user-images.githubusercontent.com/20772857/35281588-8a199156-0053-11e8-8a96-65df8b62bf32.jpg)

**Comment by kuznetsoffandrey** [comment]
Added

**Comment by teamdocs** [comment]
Yes, this works now. But I guess my initial bug report was not clear enough. What I meant to say was:

D&d and LimitSearchArea need to display "timeout counter" (like all other image commands) **and behave like other image command.**

...so if the image is not found, it should stop with the "image not found" error (unless errorignore is used). I guess that is easy to change?

**Comment by teamdocs** [comment]
This almost works now. One remaining issue is that the image does not appear in the image search wizard:

![wizard1](https://user-images.githubusercontent.com/20772857/36150660-a6b0ee28-10c4-11e8-854a-84ef0560da2e.png)

**Comment by kuznetsoffandrey** [comment]
Will fix today. Got it

**Comment by teamdocs** [comment]
ok. Same issue for LimitSearchArea

**Comment by kuznetsoffandrey** [comment]
Fixed

**Comment by kuznetsoffandrey** [comment]
You mean blue rectangles?

**Comment by kuznetsoffandrey** [comment]
Updated. Now fixed and works

**Comment by teamdocs** [comment]
ok
