### ISSUE TITLE
After errorignore ignored an error, the address bar is greyed out/disabled (even after macro stopped)

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#32]
This is a strange side effect, this screencast shows it:
https://www.screencast.com/t/MtmAUi9ZTj

It only happens when errorignore hits an error to ignore. Starting a new macro enabled the address bar again.

**Comment by kuznetsoffandrey** [comment]
It is not greyed out now. Probably was fixed in combination with the other bug
