### ISSUE TITLE
Small tweak to loop dialog

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#6]
4. Small tweak to loop dialog, now with start+end value and has its own button (= easier to use and understand for user)

Now it is confusing. Play button starts looping if value > 1. 
Better: Separate loop button. Loop starts at the current value, and loops until max. During the run, it increments the current value.

**Comment by kuznetsoffandrey** [comment]
Fixed

**Comment by teamdocs** [comment]
Works overall, just two small issues:

- The start value should also be changeable (e. g. so user can run first from 1...3, and later from 4..7).
- Do not disable Play icon. So user can always choose to run single macro and/or loop

![loop](https://user-images.githubusercontent.com/20772857/33892194-793b7816-df58-11e7-82b8-26178ce63a02.jpg)

**Comment by teamdocs** [comment]
Nice, this works. See also #14
