### ISSUE TITLE
Support “Selenium-style” variable notation

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#7]
...in addition to the current one (to keep macros backward compatible). But if keeping backward compatible is too much work or tricky, we can also skip the backward compatibility.
Currently variables are marked as {{varname}}, but for this release, both kinds should work, later only the Selenium style-
Example:
{{myvar}}, now also: ${myvar}
Special keycodes are:
{DOWN}{ENTER} now: ${KEY_DOWN}${KEY_ENTER}
Internal vars:
Now:
{{$JSRESULT}} , now ${!JSRESULT}
 {{$COL1}}, {{$COL2}, now  ${!COL1}}, ${!COL2},
(! Indicates that it is a built-in variable, like here: https://a9t9.com/kantu/web-automation/chrome#internalvar )

**Comment by kuznetsoffandrey** [comment]
Added and tested (WebBrowserExtensions.cs)

**Comment by teamdocs** [comment]
...looks good so far, I will test this further tomorrow

**Comment by teamdocs** [comment]
I tested with with Demo-Javascript test macro and ${!Javascript} and ... are not processed. The old notation also fails. ${KEY_BACK} works. TEst macros attached


[vartest.zip](https://github.com/teamdocs/kantu2018/files/1556228/vartest.zip)
![vartest1](https://user-images.githubusercontent.com/20772857/33949713-b92d4eea-e02a-11e7-9794-7d3c8b6a97bd.jpg)

**Comment by kuznetsoffandrey** [comment]
Fixed
