### ISSUE TITLE
Add SET sidebarvisible true/false command

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#8]
SET sidebarvisible false will hide the sidebar during macro replay. At the end of the replay it will show again.

(+ add this option to editor)

Purpose: Save screen real estate on smaller screen screen.

This should be easy to do, but if it is tricky for any reason, let me know.

Sidebar (click on it hides it, but currently no way to hide it from macro):

![sidebar1](https://user-images.githubusercontent.com/20772857/33390384-0efd0874-d536-11e7-9022-65616747f785.jpg)

Sidebar hidden:

![sidebar2](https://user-images.githubusercontent.com/20772857/33390418-24d946da-d536-11e7-8769-baac0b4f0bf1.jpg)

**Comment by kuznetsoffandrey** [comment]
Added

**Comment by teamdocs** [comment]
Hmm... it does not work for me, see this screenshot

![doesnothide](https://user-images.githubusercontent.com/20772857/33907601-f5133546-df85-11e7-8ce5-25fc2de24ecf.jpg)

**Comment by kuznetsoffandrey** [comment]
Set it to FALSE, upper case

**Comment by kuznetsoffandrey** [comment]
This and errorignore will have this problem. Will fix this case

**Comment by kuznetsoffandrey** [comment]
Fixed
