### ISSUE TITLE
Add default values for proxy and user agent to the settings dialog

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#9]
...otherwise users can not test during replay. (not in spec => bonus)

The mockup should explain it (at the same time you can remove the "Recording mode" part. It is not required here, as it is on the front page)

![defaultsettings](https://user-images.githubusercontent.com/20772857/33670907-75dd3634-daa6-11e7-97e5-612d2b4c2713.jpg)

**Comment by kuznetsoffandrey** [comment]
Added and implemented

**Comment by teamdocs** [comment]
ok but see #13
